---
- name: Run apt-get update
  apt:
    update_cache: yes
    force_apt_get: yes
  listen: apt_update

- name: Restart wireguard
  service:
    name: "wg-quick@wg0"
    state: restarted
  listen: wireguard_restart

- name: Reboot host
  reboot:
  listen: host_reboot
